In [1]:
import numpy as np
import pandas as pd

### Creating a dataframe

In [6]:
data= {
    "Name":["Raj","Rahul","teena","Meena","Sona"],
    "Age" :[20,30,40,18,16],
    "City":["Delhi","Mumbai","gujrat","Tamilnadu","mumbai"],
    "Salary":[20000,18000,21000,100000,15000]
}
df2=pd.DataFrame(data)
df2

    Name  Age       City  Salary
0    Raj   20      Delhi   20000
1  Rahul   30     Mumbai   18000
2  teena   40     gujrat   21000
3  Meena   18  Tamilnadu  100000
4   Sona   16     mumbai   15000

In [7]:
data=[
    ["Raj",20,"Delhi",20000],
    ['Rahul',30,"Mumbai",18000],
    ["Teena",40,"Gujrat",21000],
    ["Meena",18,"Tamilnadu",100000]
]
colomns=['Name','Age','City','Salary']
df=pd.DataFrame(data=data,columns=colomns)

### Selecting And indexing of columns

In [8]:
df["Name"]

0      Raj
1    Rahul
2    Teena
3    Meena
Name: Name, dtype: object

In [34]:
df[['Name','Age']]     ## We Can seclect multiple columns

    Name  Age
0    Raj   20
1  Rahul   30
2  Teena   40
3  Meena   18

### Creating a new Columns

    Name  Age       City  Salary
0    Raj   20      Delhi   20000
1  Rahul   30     Mumbai   18000
2  Teena   40     Gujrat   21000
3  Meena   18  Tamilnadu  100000

In [36]:
df["Designation"]=['doctor','engineer','sainik','police']
df

    Name  Age       City  Salary Designation
0    Raj   20      Delhi   20000      doctor
1  Rahul   30     Mumbai   18000    engineer
2  Teena   40     Gujrat   21000      sainik
3  Meena   18  Tamilnadu  100000      police

###  Removind Columns

In [14]:
df

    Name  Age       City  Salary
0    Raj   20      Delhi   20000
1  Rahul   30     Mumbai   18000
2  Teena   40     Gujrat   21000
3  Meena   18  Tamilnadu  100000

In [25]:
df.drop('Salary',axis=1)        ## paased me copy of the data frame   if we do use of inplace

    Name  Age       City
0    Raj   20      Delhi
1  Rahul   30     Mumbai
2  Teena   40     Gujrat
3  Meena   18  Tamilnadu

In [39]:
df

    Name  Age       City  Salary
0    Raj   20      Delhi   20000
1  Rahul   30     Mumbai   18000
2  Teena   40     Gujrat   21000
3  Meena   18  Tamilnadu  100000

In [21]:
df.drop(["Name","Age"], axis=1)         ## we can remove multiple data from col

        City  Salary
0      Delhi   20000
1     Mumbai   18000
2     Gujrat   21000
3  Tamilnadu  100000

In [41]:
df

    Name  Age       City  Salary
0    Raj   20      Delhi   20000
1  Rahul   30     Mumbai   18000
2  Teena   40     Gujrat   21000
3  Meena   18  Tamilnadu  100000

In [42]:
df.drop([0],axis=0)           ## we can drop of rows also

    Name  Age       City  Salary
1  Rahul   30     Mumbai   18000
2  Teena   40     Gujrat   21000
3  Meena   18  Tamilnadu  100000

### Selecting Of Row

In [43]:
df.loc[0]

Name        Raj
Age          20
City      Delhi
Salary    20000
Name: 0, dtype: object

In [44]:
df.loc[[2,3]]           ### here have an iloc[] they work same as loc

    Name  Age       City  Salary
2  Teena   40     Gujrat   21000
3  Meena   18  Tamilnadu  100000

### Selecting Subsets of Rows and Columns

In [45]:
df

    Name  Age       City  Salary
0    Raj   20      Delhi   20000
1  Rahul   30     Mumbai   18000
2  Teena   40     Gujrat   21000
3  Meena   18  Tamilnadu  100000

In [46]:
df.loc[[2,3]][["City","Salary"]]
# df.loc[[2,3]][["Name"]]

        City  Salary
2     Gujrat   21000
3  Tamilnadu  100000

### Conditional Selection

In [47]:
df[(df['Age']>=30 )& (df["City"]=="Gujrat")]

    Name  Age    City  Salary
2  Teena   40  Gujrat   21000

In [48]:
df[df['Age']>=30 ]

    Name  Age    City  Salary
1  Rahul   30  Mumbai   18000
2  Teena   40  Gujrat   21000

In [49]:
df[df['Salary']>20000]

    Name  Age       City  Salary
2  Teena   40     Gujrat   21000
3  Meena   18  Tamilnadu  100000

In [50]:
df

    Name  Age       City  Salary
0    Raj   20      Delhi   20000
1  Rahul   30     Mumbai   18000
2  Teena   40     Gujrat   21000
3  Meena   18  Tamilnadu  100000

In [51]:

df[['Salary','Age','Name']]

   Salary  Age   Name
0   20000   20    Raj
1   18000   30  Rahul
2   21000   40  Teena
3  100000   18  Meena

    Name  Age    City  Salary
1  Rahul   30  Mumbai   18000