In [2]:
import numpy as np 
import pandas as pd

### Mersing Two Dataframe

In [3]:
employees=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'Name':['raj','rahul','manju','Rani','Aman'],
    'Department':['HR','IT','Finance','IT','HR']
})

Salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'Salary':[12555,6664,7000,533322,90000],
    'Bonus':[12,33,55,22,33]
})

In [4]:
employees

   employee_id   Name Department
0            1    raj         HR
1            2  rahul         IT
2            3  manju    Finance
3            4   Rani         IT
4            5   Aman         HR

In [5]:
Salaries

   employee_id  Salary  Bonus
0            1   12555     12
1            2    6664     33
2            3    7000     55
3            6  533322     22
4            7   90000     33

In [9]:
pd.merge(employees,Salaries)

   employee_id   Name Department  Salary  Bonus
0            1    raj         HR   12555     12
1            2  rahul         IT    6664     33
2            3  manju    Finance    7000     55

In [11]:
pd.merge(employees,Salaries,on="employee_id")

   employee_id   Name Department  Salary  Bonus
0            1    raj         HR   12555     12
1            2  rahul         IT    6664     33
2            3  manju    Finance    7000     55

In [13]:
pd.merge(employees,Salaries,on="employee_id",how='outer')

   employee_id   Name Department    Salary  Bonus
0            1    raj         HR   12555.0   12.0
1            2  rahul         IT    6664.0   33.0
2            3  manju    Finance    7000.0   55.0
3            4   Rani         IT       NaN    NaN
4            5   Aman         HR       NaN    NaN
5            6    NaN        NaN  533322.0   22.0
6            7    NaN        NaN   90000.0   33.0

In [14]:
pd.merge(employees,Salaries,on="employee_id",how='left')

   employee_id   Name Department   Salary  Bonus
0            1    raj         HR  12555.0   12.0
1            2  rahul         IT   6664.0   33.0
2            3  manju    Finance   7000.0   55.0
3            4   Rani         IT      NaN    NaN
4            5   Aman         HR      NaN    NaN

In [15]:
pd.merge(employees,Salaries,on="employee_id",how='right')

   employee_id   Name Department  Salary  Bonus
0            1    raj         HR   12555     12
1            2  rahul         IT    6664     33
2            3  manju    Finance    7000     55
3            6    NaN        NaN  533322     22
4            7    NaN        NaN   90000     33

In [17]:
df1=pd.DataFrame({
    'A':[1,2,3],
    'B':[5,3,1],
    'C':[8,2,1]
})

df2=pd.DataFrame({
    'A':[1,2,3],
    'B':[5,3,1],
    'C':[1,4,1]
})

In [23]:
pd.concat([df1,df2],axis=1)

   A  B  C  A  B  C
0  1  5  8  1  5  1
1  2  3  2  2  3  4
2  3  1  1  3  1  1

In [24]:
pd.concat([df1,df2])

   A  B  C
0  1  5  8
1  2  3  2
2  3  1  1
0  1  5  1
1  2  3  4
2  3  1  1

In [29]:
A=pd.DataFrame({
 'name':['Raj','Rohan','payal'],
},index=[1,2,3])

B=pd.DataFrame({
 'Score':[85,40,75],
},index=[2,3,4])

In [34]:
A.join(B,how ='right')

    name  Score
2  Rohan     85
3  payal     40
4    NaN     75