### Filling Missing Data

### Finding Missing Data

In [1]:
import numpy as np
import pandas as pd

In [3]:
data={
    'A':[1,np.nan,3,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  NaN  2  2.0  NaN
2  3.0  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [12]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True
4  False  False   True  False

In [13]:
df.isna().sum()

A    0
B    1
C    2
D    3
dtype: int64

In [14]:
df.isna().any()

A    False
B     True
C     True
D     True
dtype: bool

### Removing Missing Data

In [ ]:
df.dropna(thresh=4)    ## thresh use for how much nan value

     A  B    C    D
0  1.0  1  1.0  1.0

In [25]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

### Filling Missing Data

In [26]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  NaN  2  2.0  NaN
2  3.0  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
df.fillna(df.mean())

      A  B    C    D
0  1.00  1  1.0  1.0
1  3.25  2  2.0  3.0
2  3.00  3  3.0  3.0
3  4.00  4  2.0  3.0
4  5.00  5  2.0  5.0

In [32]:
value={'A':200,'B':100,'C':129,'D':788}
df.fillna(value=value)

       A  B      C      D
0    1.0  1    1.0    1.0
1  200.0  2    2.0  788.0
2    3.0  3    3.0  788.0
3    4.0  4  129.0  788.0
4    5.0  5  129.0    5.0